---
title: "ExampleForms"
author: "Wells"
date: "7/22/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(knitr)
library(readr)
library(dict)
library(fs)
```


```{r}
# Import csv's as a dict
#tessting
forms_dict<-dict()
for (i in 0:495){
  name<-paste( "Form_Data/",toString(i),"forms0.csv" , sep = "")
  if (file.exists(name)==TRUE){
    forms[[i]]<-read_csv(name,col_names = FALSE)
  }
}
```

```{r}
# Imprt csv's as one data frame
mydir = "Form_Data/"
files<-dir_ls(mydir)

forms<-files %>% map_dfr(read_csv, col_names = F, col_types = cols(.default = "c"))


```

```{r}
#Rename columns
forms <- as_tibble(forms)

forms<-rename(forms, form = X1, hash = X2, inverse = X3, dinverse = X4, rank = X5, PF = X6, rank_diff = X7, stablity = X8, tries = X9)

```

```{r}
#Treat rank and pfaffian as numbers
forms<- forms %>% mutate(rank = as.numeric(rank), PF = map_dbl(PF, ~eval(parse(text = .x))), stablity = as.numeric(stablity), tries = as.numeric(tries),  rank_diff = as.numeric(rank_diff))

```

```{r}
ori_forms <- forms  %>% filter(tries == 0)
   
#ggplot(aes(x = rank))+geom_histogram(binwidth = 5)
```

```{r}
ori_forms %>% count(rank, stablity) %>% group_by(rank) %>% mutate(prop = n/ sum(n)) %>% filter(stablity == 0) %>% mutate(prop = 1-prop) %>% ggplot(aes( x = rank, y = prop)) +
   geom_point() +
   theme_bw()
```
```{r}
ori_forms %>% count(rank, stablity) %>% group_by(rank) %>% mutate(prop = n/ sum(n)) %>% filter(stablity == -1) %>% mutate(prop = 1-prop) %>% ggplot(aes( x = rank, y = prop)) +
   geom_point() +
   geom_smooth() +
   theme_bw()
```

```{r}
forms_invert<-forms %>% count(rank, invertible) %>% group_by(rank) %>% mutate(prop = n/ sum(n))

 forms_invert %>% filter(invertible =="True") %>% 
   ggplot(aes( x = rank, y = prop)) +
   geom_point()+
   geom_smooth()

```

```{r}
forms_stable<-forms %>% count(rank, stable) %>% group_by(rank) %>% mutate(prop = n/ sum(n))

 forms_stable %>% filter(stable =="True") %>% 
   ggplot(aes( x = rank, y = prop)) +
   geom_point()+
   geom_vline( xintercept = 32)+
   geom_smooth()

```


```{r}
forms_pf<-forms %>% filter(PF > -2 & PF < 5  )

forms_pf %>% ggplot( aes ( x = PF)) + geom_histogram(bins = 20, color = "white")
```

```{r}
forms_538<-forms_pf %>% filter(form == "(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)")
```

